name: roomcard
description: "A new Flutter project."
publish_to: "none"
version: 4.10.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6 # 路由状态管理库
  auto_size_text: ^3.0.0 #自适应text
  package_info_plus: ^8.3.0 #包信息
  device_info_plus: ^11.4.0 #设备信息，和包名信息不用的是可以拿到设备的一些系统版本号之类的。
  flutter_screenutil: 5.9.3 #屏幕自适应
  flutter_easyloading: ^3.0.5 #加载loading
  pull_to_refresh: ^2.0.0 # list的下拉上拉刷新
  logger: ^2.4.0 # 打印日志
  flutter_launcher_icons: ^0.14.4 #app图标
  flutter_native_splash: ^2.4.6 #启动图
  cached_network_image: ^3.4.1 # 图片缓存加载
  pinput: ^5.0.1 #pin 输入框
  image_picker: ^1.1.2 #图片选择
  webview_flutter: ^4.13.0 # webview
  flutter_inappwebview: ^6.1.5 #webview
  dio: ^5.8.0+1 # 网络请求
  shared_preferences: ^2.5.3 #本地存储
  event_bus: ^2.0.1 # 全局共享事件
  gap: ^3.0.1 # 占位空间
  url_launcher: ^6.3.1 #url打开和检查
  lottie: ^3.3.1 #Lottie动画
  permission_handler: ^12.0.0+1 # 权限请求（安卓需要）
  gallery_saver_plus: ^3.2.4 #保存本地图片
  carousel_slider: ^5.0.0 #轮播图
  crypto: ^3.0.3 # md5等等各种加密
  decimal: ^3.2.4 #数据类型控制
  connectivity_plus: ^6.1.4 # 网络状态监听
  pretty_dio_logger: ^1.3.1 # dio库扩展打印日志
  flutter_staggered_animations: ^1.1.1 # 列表动画
  intl: ^0.20.2
  encrypt: ^5.0.3 # AES加密
  marquee: ^2.3.0 # 跑马灯
  shimmer: ^3.0.0 # 骨架屏
  flutter_animate: ^4.5.2 #动画
  flutter_svg: ^2.1.0 #svg 加载
  pub_semver: ^2.2.0 #版本判断
  flutter_image_compress: ^2.4.0 #图片压缩
  wechat_assets_picker: ^9.5.1 #文件选择
  animated_toggle_switch: ^0.8.5 #滑动开关
  date_format: ^2.0.9 #时间格式化工具
  flutter_html: ^3.0.0 #展示富文本
  flutter_html_table: ^3.0.0
  dropdown_button2: ^2.3.9 #下拉按钮
  path_provider: ^2.1.5
  flutter_popup: ^3.3.9 # 气泡弹窗
  captcha_plugin_flutter: 1.1.6
  custom_pop_up_menu: ^1.2.4
  flutter_secure_storage: ^9.2.4
  stack_trace: ^1.11.1
  phone_numbers_parser: ^9.0.1
  timezone: ^0.9.3
  flutter_keyboard_visibility: ^6.0.0
  uuid: ^4.3.2

# Flutter Launcher Icons 配置
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon/icon-1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon/icon-1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_icon/icon-1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon/icon-1024.png"

# Flutter Native Splash 启动页配置
flutter_native_splash:
  # 启动页背景图片
  image: assets/images/launch/startBg.png
  # 背景颜色（如果图片没有覆盖整个屏幕）
  color: "#000000"
  # 图片填充模式
  image_dark: assets/images/launch/startBg.png
  color_dark: "#000000"
  # 是否全屏显示
  fullscreen: true
  # 是否显示状态栏
  android_12:
    image: assets/images/launch/startBg.png
    icon_background_color: "#000000"
    image_dark: assets/images/launch/startBg.png
    icon_background_color_dark: "#000000"
  # iOS配置
  ios: true
  # Android配置
  android: true
  # Web配置
  web: false
  # 防止白色闪烁的配置
  android_gravity: center
  ios_content_mode: center

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # 本地开发环境变量， 不要删除， 如果报错，在pubspec.yaml文件同层目录创建一个 .env.dev空白文件即可。
    # - .env.dev
    - assets/
    - assets/app_config/
    - assets/images/
    - assets/images/launch/
    - assets/images/bottom_nav/
    - assets/images/public/
    - assets/images/home/
    - assets/images/game/
    - lib/r.dart

  fonts:
    - family: PingFangSC
      fonts:
        - asset: assets/fonts/PingFangSC-Regular.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/regular.ttf
    - family: webfont
      fonts:
        - asset: assets/fonts/roboto-semibold-webfont.ttf
    - family: numberfont
      fonts:
        - asset: assets/fonts/numberfont.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/
  filename: r.dart
  classname: R
