import 'package:roomcard/utils/Tools.dart';
import 'package:roomcard/utils/values/enums.dart';

enum Country {
  zg(name: '中国', code: '86', ehName: 'China'),
  twzg(name: '中国台湾', code: '886', ehName: 'Taiwan'),
  xgzg(name: '中国香港', code: '852', ehName: 'Hongkong'),
  adeghg(name: '安道尔共和国', code: '376', ehName: 'Andorra'),
  alblhqzg(name: '阿拉伯联合酋长国', code: '971', ehName: 'UnitedArabEmirates'),
  afh(name: '阿富汗', code: '93', ehName: 'Afghanistan'),
  atghbbd(name: '安提瓜和巴布达', code: '1268', ehName: 'AntiguaandBarbuda'),
  agld(name: '安圭拉岛', code: '1264', ehName: 'Anguilla'),
  aebny(name: '阿尔巴尼亚', code: '355', ehName: 'Albania'),
  amny(name: '阿美尼亚', code: '374', ehName: 'Armenia'),
  als(name: '阿森松', code: '247', ehName: 'Ascension'),
  agl(name: '安哥拉', code: '244', ehName: 'Angola'),
  agt(name: '阿根廷', code: '54', ehName: 'Argentina'),
  adl(name: '奥地利', code: '43', ehName: 'Austria'),
  adly(name: '澳大利亚', code: '61', ehName: 'Australia'),
  asbj(name: '阿塞拜疆', code: '994', ehName: 'Azerbaijan'),
  bbds(name: '巴巴多斯', code: '1246', ehName: 'Barbados'),
  mjlg(name: '孟加拉国', code: '880', ehName: 'Bangladesh'),
  bls(name: '比利时', code: '32', ehName: 'Belgium'),
  bjnfs(name: '布基纳法索', code: '226', ehName: 'Burkina-faso'),
  bjly(name: '保加利亚', code: '359', ehName: 'Bulgaria'),
  bl(name: '巴林', code: '973', ehName: 'Bahrain'),
  bld(name: '布隆迪', code: '257', ehName: 'Burundi'),
  beil(name: '贝宁', code: '229', ehName: 'Benin'),
  blst(name: '巴勒斯坦', code: '970', ehName: 'Palestine'),
  bmdqd(name: '百慕大群岛', code: '1441', ehName: 'BermudaIs.'),
  wl(name: '文莱', code: '673', ehName: 'Brunei'),
  blwy(name: '玻利维亚', code: '591', ehName: 'Bolivia'),
  bx(name: '巴西', code: '55', ehName: 'Brazil'),
  bhm(name: '巴哈马', code: '1242', ehName: 'Bahamas'),
  bcwn(name: '博茨瓦纳', code: '267', ehName: 'Botswana'),
  bels(name: '白俄罗斯', code: '375', ehName: 'Belarus'),
  blz(name: '伯利兹', code: '501', ehName: 'Belize'),
  jnd(name: '加拿大', code: '1', ehName: 'Canada'),
  kmqd(name: '开曼群岛', code: '1345', ehName: 'CaymanIs.'),
  zfghg(name: '中非共和国', code: '236', ehName: 'CentralAfricanRepublic'),
  gg(name: '刚果', code: '242', ehName: 'Congo'),
  rs(name: '瑞士', code: '41', ehName: 'Switzerland'),
  kkqd(name: '库克群岛', code: '682', ehName: 'CookIs.'),
  zl(name: '智利', code: '56', ehName: 'Chile'),
  kml(name: '喀麦隆', code: '237', ehName: 'Cameroon'),
  glby(name: '哥伦比亚', code: '57', ehName: 'Colombia'),
  gsdlj(name: '哥斯达黎加', code: '506', ehName: 'CostaRica'),
  jk(name: '捷克', code: '420', ehName: 'Czech'),
  gb(name: '古巴', code: '53', ehName: 'Cuba'),
  spls(name: '塞浦路斯', code: '357', ehName: 'Cyprus'),
  jiek(name: '捷克', code: '420', ehName: 'CzechRepublic'),
  dg(name: '德国', code: '49', ehName: 'Germany'),
  jbt(name: '吉布提', code: '253', ehName: 'Djibouti'),
  dm(name: '丹麦', code: '45', ehName: 'Denmark'),
  dmnjghg(name: '多米尼加共和国', code: '1890', ehName: 'DominicaRep.'),
  aejly(name: '阿尔及利亚', code: '213', ehName: 'Algeria'),
  egde(name: '厄瓜多尔', code: '593', ehName: 'Ecuador'),
  asny(name: '爱沙尼亚', code: '372', ehName: 'Estonia'),
  ej(name: '埃及', code: '20', ehName: 'Egypt'),
  xby(name: '西班牙', code: '34', ehName: 'Spain'),
  aseby(name: '埃塞俄比亚', code: '251', ehName: 'Ethiopia'),
  fl(name: '芬兰', code: '358', ehName: 'Finland'),
  fj(name: '斐济', code: '679', ehName: 'Fiji'),
  fg(name: '法国', code: '33', ehName: 'France'),
  jp(name: '加蓬', code: '241', ehName: 'Gabon'),
  yg(name: '英国', code: '44', ehName: 'UnitedKiongdom'),
  glnd(name: '格林纳达', code: '1809', ehName: 'Grenada'),
  gljy(name: '格鲁吉亚', code: '995', ehName: 'Georgia'),
  fsgyn(name: '法属圭亚那', code: '594', ehName: 'FrenchGuiana'),
  jn(name: '加纳', code: '233', ehName: 'Ghana'),
  zblt(name: '直布罗陀', code: '350', ehName: 'Gibraltar'),
  gby(name: '冈比亚', code: '220', ehName: 'Gambia'),
  jny(name: '几内亚', code: '224', ehName: 'Guinea'),
  xl(name: '希腊', code: '30', ehName: 'Greece'),
  wdml(name: '危地马拉', code: '502', ehName: 'Guatemala'),
  gd(name: '关岛', code: '1671', ehName: 'Guam'),
  gyn(name: '圭亚那', code: '592', ehName: 'Guyana'),
  hdls(name: '洪都拉斯', code: '504', ehName: 'Honduras'),
  hd(name: '海地', code: '509', ehName: 'Haiti'),
  xyl(name: '匈牙利', code: '36', ehName: 'Hungary'),
  ydnxy(name: '印度尼西亚', code: '62', ehName: 'Indonesia'),
  ael(name: '爱尔兰', code: '353', ehName: 'Ireland'),
  ysl(name: '以色列', code: '972', ehName: 'Israel'),
  yd(name: '印度', code: '91', ehName: 'India'),
  ylk(name: '伊拉克', code: '964', ehName: 'Iraq'),
  yl(name: '伊朗', code: '98', ehName: 'Iran'),
  bd(name: '冰岛', code: '354', ehName: 'Iceland'),
  ydl(name: '意大利', code: '39', ehName: 'Italy'),
  ktdw(name: '科特迪瓦', code: '225', ehName: 'IvoryCoast'),
  ymj(name: '牙买加', code: '1876', ehName: 'Jamaica'),
  yued(name: '约旦', code: '962', ehName: 'Jordan'),
  rb(name: '日本', code: '81', ehName: 'Japan'),
  kny(name: '肯尼亚', code: '254', ehName: 'Kenya'),
  jejst(name: '吉尔吉斯坦', code: '331', ehName: 'Kyrgyzstan'),
  jpz(name: '柬埔寨', code: '855', ehName: 'Kampuchea(Cambodia)'),
  cx(name: '朝鲜', code: '850', ehName: 'NorthKorea'),
  hg(name: '韩国', code: '82', ehName: 'Korea'),
  ktdwghg(name: '科特迪瓦共和国', code: '225', ehName: 'RepublicofIvoryCoast'),
  kwt(name: '科威特', code: '965', ehName: 'Kuwait'),
  hskst(name: '哈萨克斯坦', code: '327', ehName: 'Kazakstan'),
  lw(name: '老挝', code: '856', ehName: 'Laos'),
  lbn(name: '黎巴嫩', code: '961', ehName: 'Lebanon'),
  slxy(name: '圣卢西亚', code: '1758', ehName: 'St.Lucia'),
  lzdsd(name: '列支敦士登', code: '423', ehName: 'Liechtenstein'),
  sllk(name: '斯里兰卡', code: '94', ehName: 'SriLanka'),
  lbly(name: '利比里亚', code: '231', ehName: 'Liberia'),
  lst(name: '莱索托', code: '266', ehName: 'Lesotho'),
  ltw(name: '立陶宛', code: '370', ehName: 'Lithuania'),
  lsb(name: '卢森堡', code: '352', ehName: 'Luxembourg'),
  ltwy(name: '拉脱维亚', code: '371', ehName: 'Latvia'),
  lby(name: '利比亚', code: '218', ehName: 'Libya'),
  mlg(name: '摩洛哥', code: '212', ehName: 'Morocco'),
  mng(name: '摩纳哥', code: '377', ehName: 'Monaco'),
  medw(name: '摩尔多瓦', code: '373', ehName: 'Moldova,Republicof'),
  mdjsj(name: '马达加斯加', code: '261', ehName: 'Madagascar'),
  ml(name: '马里', code: '223', ehName: 'Mali'),
  md(name: '缅甸', code: '95', ehName: 'Burma'),
  mg(name: '蒙古', code: '976', ehName: 'Mongolia'),
  am(name: '澳门', code: '853', ehName: 'Macao'),
  mtsstd(name: '蒙特塞拉特岛', code: '1664', ehName: 'MontserratIs'),
  met(name: '马耳他', code: '356', ehName: 'Malta'),
  mlynqd(name: '马里亚那群岛', code: '1670', ehName: 'MarianaIs'),
  mtnk(name: '马提尼克', code: '596', ehName: 'Martinique'),
  mlqs(name: '毛里求斯', code: '230', ehName: 'Mauritius'),
  medf(name: '马尔代夫', code: '960', ehName: 'Maldives'),
  mlw(name: '马拉维', code: '265', ehName: 'Malawi'),
  mxg(name: '墨西哥', code: '52', ehName: 'Mexico'),
  mlxy(name: '马来西亚', code: '60', ehName: 'Malaysia'),
  msbk(name: '莫桑比克', code: '258', ehName: 'Mozambique'),
  nmby(name: '纳米比亚', code: '264', ehName: 'Namibia'),
  nre(name: '尼日尔', code: '977', ehName: 'Niger'),
  nrly(name: '尼日利亚', code: '234', ehName: 'Nigeria'),
  njlg(name: '尼加拉瓜', code: '505', ehName: 'Nicaragua'),
  hl(name: '荷兰', code: '31', ehName: 'Netherlands'),
  nw(name: '挪威', code: '47', ehName: 'Norway'),
  nbe(name: '尼泊尔', code: '977', ehName: 'Nepal'),
  hsadls(name: '荷属安的列斯', code: '599', ehName: 'NetheriandsAntilles'),
  nl(name: '瑙鲁', code: '674', ehName: 'Nauru'),
  xxl(name: '新西兰', code: '64', ehName: 'NewZealand'),
  amai(name: '阿曼', code: '968', ehName: 'Oman'),
  bnm(name: '巴拿马', code: '507', ehName: 'Panama'),
  mil(name: '秘鲁', code: '51', ehName: 'Peru'),
  fsblnxy(name: '法属玻利尼西亚', code: '689', ehName: 'FrenchPolynesia'),
  bbyxjny(name: '巴布亚新几内亚', code: '675', ehName: 'PapuaNewCuinea'),
  flb(name: '菲律宾', code: '63', ehName: 'Philippines'),
  bjst(name: '巴基斯坦', code: '92', ehName: 'Pakistan'),
  bol(name: '波兰', code: '48', ehName: 'Poland'),
  bdlg(name: '波多黎各', code: '1787', ehName: 'PuertoRico'),
  pty(name: '葡萄牙', code: '351', ehName: 'Portugal'),
  blg(name: '巴拉圭', code: '595', ehName: 'Paraguay'),
  kte(name: '卡塔尔', code: '974', ehName: 'Qatar'),
  lnw(name: '留尼旺', code: '262', ehName: 'Reunion'),
  lmny(name: '罗马尼亚', code: '40', ehName: 'Romania'),
  els(name: '俄罗斯', code: '7', ehName: 'Russia'),
  stalb(name: '沙特阿拉伯', code: '966', ehName: 'SaudiArabia'),
  slmqd(name: '所罗门群岛', code: '677', ehName: 'SolomonIs'),
  sse(name: '塞舌尔', code: '248', ehName: 'Seychelles'),
  sd(name: '苏丹', code: '249', ehName: 'Sudan'),
  rd(name: '瑞典', code: '46', ehName: 'Sweden'),
  xjp(name: '新加坡', code: '65', ehName: 'Singapore'),
  slwny(name: '斯洛文尼亚', code: '386', ehName: 'Slovenia'),
  slfk(name: '斯洛伐克', code: '421', ehName: 'Slovakia'),
  slla(name: '塞拉利昂', code: '232', ehName: 'SierraLeone'),
  smln(name: '圣马力诺', code: '378', ehName: 'SanMarino'),
  dsmym(name: '东萨摩亚(美)', code: '684', ehName: 'SamoaEastern'),
  xsmy(name: '西萨摩亚', code: '685', ehName: 'SanMarino'),
  snje(name: '塞内加尔', code: '221', ehName: 'Senegal'),
  sml(name: '索马里', code: '252', ehName: 'Somali'),
  sln(name: '苏里南', code: '597', ehName: 'Suriname'),
  sdmhplxb(name: '圣多美和普林西比', code: '239', ehName: 'SaoTomeandPrincipe'),
  sewd(name: '萨尔瓦多', code: '503', ehName: 'EISalvador'),
  xly(name: '叙利亚', code: '963', ehName: 'Syria'),
  swsl(name: '斯威士兰', code: '268', ehName: 'Swaziland'),
  zd(name: '乍得', code: '235', ehName: 'Chad'),
  duog(name: '多哥', code: '228', ehName: 'Togo'),
  tg(name: '泰国', code: '66', ehName: 'Thailand'),
  tjkst(name: '塔吉克斯坦', code: '992', ehName: 'Tajikstan'),
  tkmst(name: '土库曼斯坦', code: '993', ehName: 'Turkmenistan'),
  tns(name: '突尼斯', code: '216', ehName: 'Tunisia'),
  tj(name: '汤加', code: '676', ehName: 'Tonga'),
  teq(name: '土耳其', code: '90', ehName: 'Turkey'),
  tlndhdbg(name: '特立尼达和多巴哥', code: '1809', ehName: 'TrinidadandTobago'),
  tsny(name: '坦桑尼亚', code: '255', ehName: 'Tanzania'),
  wkl(name: '乌克兰', code: '380', ehName: 'Ukraine'),
  wgd(name: '乌干达', code: '256', ehName: 'Uganda'),
  meig(name: '美国', code: '1', ehName: 'UnitedStatesofAmerica'),
  wlg(name: '乌拉圭', code: '598', ehName: 'Uruguay'),
  wzbkst(name: '乌兹别克斯坦', code: '233', ehName: 'Uzbekistan'),
  swstd(name: '圣文森特岛', code: '1784', ehName: 'SaintVincent'),
  wnrl(name: '委内瑞拉', code: '58', ehName: 'Venezuela'),
  yn(name: '越南', code: '84', ehName: 'Vietnam'),
  ym(name: '也门', code: '967', ehName: 'Yemen'),
  nslf(name: '南斯拉夫', code: '381', ehName: 'Yugoslavia'),
  nf(name: '南非', code: '27', ehName: 'SouthAfrica'),
  zby(name: '赞比亚', code: '260', ehName: 'Zambia'),
  zye(name: '扎伊尔', code: '243', ehName: 'Zaire'),
  jbbw(name: '津巴布韦', code: '263', ehName: 'Zimbabwe');

  const Country({required this.name, required this.code, required this.ehName});

  final String name;
  final String code;
  final String ehName;

  static Country valueOf(String code) {
    return Country.values.firstWhere((element) => element.code == code);
  }

  static List<String> nameForLanguageEn = const [
    "China",
    "Taiwan",
    "Hong Kong",
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Ascension",
    "Angola",
    "Argentina",
    "Austria",
    "Australia",
    "Azerbaijan",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Palestine",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Brazil",
    "Bahamas",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cayman Islands",
    "China African Republic",
    "Congo",
    "Switzerland",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "Colombia",
    "Costa Rica",
    "Czech Republic",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "France",
    "Gabon",
    "United Kingdom",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Ghana",
    "Gibraltar",
    "The Gambia",
    "Guinea",
    "Greece",
    "Guatemala",
    "Guam",
    "Guyana",
    "Honduras",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "India",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Côte d'Ivoire",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "North Korea",
    "South Korea",
    "Republic of Côte d'Ivoire",
    "Kuwait",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg ",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Madagascar",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macau",
    "Montserrat",
    "Malta",
    "Mariana Islands",
    "Martinique",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Netherlands Antilles",
    "Nauru",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland ",
    "Puerto Rico",
    "Portugal",
    "Paraguay",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Slovenia",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Eastern Samoa (USA)",
    "Western Samoa Asia",
    "Senegal",
    "Somalia",
    "Suriname",
    "Sao Tome and Principe",
    "El Salvador",
    "Syria",
    "Swaziland",
    "Chad",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Togo Bago",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "St. Vincent",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Yugoslavia",
    "South Africa",
    "Zambia",
    "Zaire",
    "Zimbabwe",
  ];

  static List<String> nameForLanguageEs = const [
    "China",
    "Taiwán",
    "Hong Kong",
    "Andorra",
    "Emiratos Árabes Unidos",
    "Afganistán",
    "Antigua y Barbuda",
    "Anguila",
    "Albania",
    "Armenia",
    "Ascensión",
    "Angola",
    "Argentina",
    "Austria",
    "Australia",
    "Azerbaiyán",
    "Barbados",
    "Bangladesh",
    "Bélgica",
    "Burkina Faso",
    "Bulgaria",
    "Bahrein",
    "Burundi",
    "Benin",
    "Palestina",
    "Bermudas",
    "Brunei",
    "Bolivia",
    "Brasil",
    "Bahamas",
    "Botswana",
    "Bielorrusia",
    "Belice",
    "Canadá",
    "Islas Caimán",
    "China República Africana",
    "Congo",
    "Suiza",
    "Islas Cook",
    "Chile",
    "Camerún",
    "Colombia",
    "Costa Rica",
    "República Checa",
    "Cuba",
    "Chipre",
    "República Checa",
    "Alemania",
    "Djibouti",
    "Dinamarca",
    "República Dominicana",
    "Argelia",
    "Ecuador",
    "Estonia",
    "Egipto",
    "España",
    "Etiopía",
    "Finlandia",
    "Fiji",
    "Francia",
    "Gabón",
    "Reino Unido",
    "Granada",
    "Georgia",
    "Guayana Francesa",
    "Ghana",
    "Gibraltar",
    "Gambia",
    "Guinea",
    "Grecia",
    "Guatemala",
    "Guam",
    "Guyana",
    "Honduras",
    "Haití",
    "Hungría",
    "Indonesia",
    "Irlanda",
    "Israel",
    "India",
    "Irak",
    "Irán",
    "Islandia",
    "Italia",
    "Costa de Marfil",
    "Jamaica",
    "Jordania",
    "Japón",
    "Kenia",
    "Kirguistán",
    "Camboya",
    "Corea del Norte",
    "Corea del Sur",
    "República de Costa de Marfil",
    "Kuwait",
    "Kazajstán",
    "Laos",
    "Líbano",
    "Santa Lucía",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lituania",
    "Luxemburgo",
    "Letonia",
    "Libia",
    "Marruecos",
    "Mónaco",
    "Moldavia",
    "Madagascar ",
    "Malí",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Montserrat",
    "Malta",
    "Islas Marianas",
    "Martinica",
    "Mauricio",
    "Maldivas",
    "Malawi",
    "México",
    "Malasia",
    "Mozambique",
    "Namibia",
    "Níger",
    "Nigeria",
    "Nicaragua",
    "Países Bajos",
    "Noruega",
    "Nepal",
    "Antillas Holandesas",
    "Nauru",
    "Nueva Zelanda",
    "Omán",
    "Panamá",
    "Perú",
    "Polinesia Francesa",
    "Papúa Nueva Guinea",
    "Filipinas",
    "Pakistán",
    "Polonia",
    "Puerto Rico",
    "Portugal",
    "Paraguay",
    "Qatar",
    "Reunión",
    "Rumania",
    "Rusia",
    "Arabia Saudita",
    "Islas Salomón",
    "Seychelles",
    "Sudán",
    "Suecia",
    "Singapur",
    "Eslovenia",
    "Eslovaquia",
    "Sierra Leona",
    "San Marino",
    "Samoa Oriental (EE.UU.)",
    "Samoa Occidental Asia",
    "Senegal",
    "Somalia",
    "Surinam",
    "Santo Tomé y Príncipe",
    "El Salvador",
    "Siria",
    "Suazilandia",
    "Chad",
    "Togo",
    "Tailandia",
    "Tayikistán",
    "Turkmenistán",
    "Túnez",
    "Tonga",
    "Turquía",
    "Trinidad y Togo Bago",
    "Tanzania",
    "Ucrania",
    "Uganda",
    "Estados Unidos",
    "Uruguay",
    "Uzbekistán",
    "San Vicente",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Yugoslavia",
    "Sudáfrica",
    "Zambia",
    "Zaire",
    "Zimbabwe",
  ];

  static List<String> nameForLanguageZh = const [
    "中国",
    "中国台湾",
    "中国香港",
    "安道尔共和国",
    "阿拉伯联合酋长国",
    "阿富汗",
    "安提瓜和巴布达",
    "安圭拉岛",
    "阿尔巴尼亚",
    "阿美尼亚",
    "阿森松",
    "安哥拉",
    "阿根廷",
    "奥地利",
    "澳大利亚",
    "阿塞拜疆",
    "巴巴多斯",
    "孟加拉国",
    "比利时",
    "布基纳法索",
    "保加利亚",
    "巴林",
    "布隆迪",
    "贝宁",
    "巴勒斯坦",
    "百慕大群岛",
    "文莱",
    "玻利维亚",
    "巴西",
    "巴哈马",
    "博茨瓦纳",
    "白俄罗斯",
    "伯利兹",
    "加拿大",
    "开曼群岛",
    "中非共和国",
    "刚果",
    "瑞士",
    "库克群岛",
    "智利",
    "喀麦隆",
    "哥伦比亚",
    "哥斯达黎加",
    "捷克",
    "古巴",
    "塞浦路斯",
    "捷克",
    "德国",
    "吉布提",
    "丹麦",
    "多米尼加共和国",
    "阿尔及利亚",
    "厄瓜多尔",
    "爱沙尼亚",
    "埃及",
    "西班牙",
    "埃塞俄比亚",
    "芬兰",
    "斐济",
    "法国",
    "加蓬",
    "英国",
    "格林纳达",
    "格鲁吉亚",
    "法属圭亚那",
    "加纳",
    "直布罗陀",
    "冈比亚",
    "几内亚",
    "希腊",
    "危地马拉",
    "关岛",
    "圭亚那",
    "洪都拉斯",
    "海地",
    "匈牙利",
    "印度尼西亚",
    "爱尔兰",
    "以色列",
    "印度",
    "伊拉克",
    "伊朗",
    "冰岛",
    "意大利",
    "科特迪瓦",
    "牙买加",
    "约旦",
    "日本",
    "肯尼亚",
    "吉尔吉斯坦",
    "柬埔寨",
    "朝鲜",
    "韩国",
    "科特迪瓦共和国",
    "科威特",
    "哈萨克斯坦",
    "老挝",
    "黎巴嫩",
    "圣卢西亚",
    "列支敦士登",
    "斯里兰卡",
    "利比里亚",
    "莱索托",
    "立陶宛",
    "卢森堡",
    "拉脱维亚",
    "利比亚",
    "摩洛哥",
    "摩纳哥",
    "摩尔多瓦",
    "马达加斯加",
    "马里",
    "缅甸",
    "蒙古",
    "澳门",
    "蒙特塞拉特岛",
    "马耳他",
    "马里亚那群岛",
    "马提尼克",
    "毛里求斯",
    "马尔代夫",
    "马拉维",
    "墨西哥",
    "马来西亚",
    "莫桑比克",
    "纳米比亚",
    "尼日尔",
    "尼日利亚",
    "尼加拉瓜",
    "荷兰",
    "挪威",
    "尼泊尔",
    "荷属安的列斯",
    "瑙鲁",
    "新西兰",
    "阿曼",
    "巴拿马",
    "秘鲁",
    "法属玻利尼西亚",
    "巴布亚新几内亚",
    "菲律宾",
    "巴基斯坦",
    "波兰",
    "波多黎各",
    "葡萄牙",
    "巴拉圭",
    "卡塔尔",
    "留尼旺",
    "罗马尼亚",
    "俄罗斯",
    "沙特阿拉伯",
    "所罗门群岛",
    "塞舌尔",
    "苏丹",
    "瑞典",
    "新加坡",
    "斯洛文尼亚",
    "斯洛伐克",
    "塞拉利昂",
    "圣马力诺",
    "东萨摩亚(美)",
    "西萨摩亚",
    "塞内加尔",
    "索马里",
    "苏里南",
    "圣多美和普林西比",
    "萨尔瓦多",
    "叙利亚",
    "斯威士兰",
    "乍得",
    "多哥",
    "泰国",
    "塔吉克斯坦",
    "土库曼斯坦",
    "突尼斯",
    "汤加",
    "土耳其",
    "特立尼达和多巴哥",
    "坦桑尼亚",
    "乌克兰",
    "乌干达",
    "美国",
    "乌拉圭",
    "乌兹别克斯坦",
    "圣文森特岛",
    "委内瑞拉",
    "越南",
    "也门",
    "南斯拉夫",
    "南非",
    "赞比亚",
    "扎伊尔",
    "津巴布韦",
  ];

  static List<String> nameForLanguagePt = const [
    "China",
    "Taiwan",
    "Hong Kong",
    "Andorra",
    "Emirados Árabes Unidos",
    "Afeganistão",
    "Antígua e Barbuda",
    "Anguila",
    "Albânia",
    "Arménia",
    "Ascensão",
    "Angola",
    "Argentina",
    "Áustria",
    "Austrália",
    "Azerbaijão",
    "Barbados",
    "Bangladesh",
    "Bélgica",
    "Burkina Faso",
    "Bulgária",
    "Bahrein",
    "Burundi",
    "Benin",
    "Palestina",
    "Bermudas",
    "Brunei",
    "Bolívia",
    "Brasil",
    "Bahamas",
    "Botswana",
    "Bielorrússia",
    "Belize",
    "Canadá",
    "Ilhas Cayman",
    "China República Africana",
    "Congo",
    "Suíça",
    "Ilhas Cook",
    "Chile",
    "Camarões",
    "Colômbia",
    "Costa Rica",
    "República Checa",
    "Cuba",
    "Chipre",
    "República Checa",
    "Alemanha",
    "Djibouti",
    "Dinamarca",
    "República Dominicana",
    "Argélia",
    "Equador",
    "Estónia",
    "Egipto",
    "Espanha",
    "Etiópia",
    "Finlândia",
    "Fiji",
    "França",
    "Gabão",
    "Reino Unido",
    "Granada",
    "Geórgia",
    "Guiana Francesa",
    "Gana",
    "Gibraltar",
    "Gâmbia",
    "Guiné",
    "Grécia",
    "Guatemala",
    "Guam",
    "Guiana",
    "Honduras",
    "Haiti",
    "Hungria",
    "Indonésia",
    "Irlanda",
    "Israel",
    "Índia",
    "Iraque",
    "Irão",
    "Islândia",
    "Itália",
    "Costa do Marfim",
    "Jamaica",
    "Jordânia",
    "Japão",
    "Quénia",
    "Quirguizistão",
    "Camboja",
    "Coreia do Norte",
    "Coreia do Sul",
    "República da Costa do Marfim",
    "Kuwait",
    "Cazaquistão",
    "Laos",
    "Líbano",
    "Santa Lúcia",
    "Liechtenstein",
    "Sri Lanka",
    "Libéria",
    "Lesoto",
    "Lituânia",
    "Luxemburgo",
    "Letónia",
    "Líbia",
    "Marrocos",
    "Mónaco",
    "Moldávia",
    "Madagáscar ",
    "Mali",
    "Mianmar",
    "Mongólia",
    "Macau",
    "Montserrat",
    "Malta",
    "Ilhas Marianas",
    "Martinica",
    "Maurícias",
    "Maldivas",
    "Malawi",
    "México",
    "Malásia",
    "Moçambique",
    "Namíbia",
    "Níger",
    "Nigéria",
    "Nicarágua",
    "Países Baixos",
    "Noruega",
    "Nepal",
    "Antilhas Holandesas",
    "Nauru",
    "Novo Zelândia",
    "Omã",
    "Panamá",
    "Peru",
    "Polinésia Francesa",
    "Papua Nova Guiné",
    "Filipinas",
    "Paquistão",
    "Polónia",
    "Porto Rico",
    "Portugal",
    "Paraguai",
    "Qatar",
    "Reunião",
    "Roménia",
    "Rússia",
    "Arábia Saudita",
    "Ilhas Salomão",
    "Seychelles",
    "Sudão",
    "Suécia",
    "Singapura",
    "Eslovénia",
    "Eslováquia",
    "Serra Leoa",
    "São Marino",
    "Samoa Oriental (EUA)",
    "Samoa Ocidental Ásia",
    "Senegal",
    "Somália",
    "Suriname",
    "São Tomé e Príncipe",
    "El Salvador",
    "Síria",
    "Suazilândia",
    "Chade",
    "Togo",
    "Tailândia",
    "Tajiquistão",
    "Turquemenistão",
    "Tunísia",
    "Tonga",
    "Turquia",
    "Trinidad e Togo Bago",
    "Tanzânia",
    "Ucrânia",
    "Uganda",
    "Estados Unidos",
    "Uruguai",
    "Uzbequistão",
    "São Vicente",
    "Venezuela",
    "Vietnã",
    "Iêmen",
    "Iugoslávia",
    "África do Sul",
    "Zâmbia",
    "Zaire",
    "Zimbábue",
  ];

  static List<String> nameForLanguageVn = const [
    "Trung Quốc",
    "Đài Loan, Trung Quốc",
    "Trung Quốc Hồng Kông",
    "Cộng hòa Andorra",
    "Các Tiểu Vương Quốc Ả Rập Thống Nhất",
    "Afghanistan",
    "Antigua và Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Thăng thiên",
    "An-gô-la",
    "Argentina",
    "Áo",
    "Châu Úc",
    "Azerbaijan",
    "Barbados",
    "Bangladesh",
    "Nước Bỉ",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Bénin",
    "Palestine",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Brazil",
    "Bahama",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Quần đảo Cayman",
    "Cộng hòa trung phi",
    "Công-gô",
    "Thụy sĩ",
    "Hòn đảo",
    "Chilê",
    "Cameroon",
    "Colombia",
    "costa rica",
    "Séc",
    "Cuba",
    "Síp",
    "Séc",
    "Nước Đức",
    "Djibouti",
    "Đan mạch",
    "Cộng hòa Dominica",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Ai Cập",
    "Tây ban nha",
    "Ethiopia",
    "Phần Lan",
    "Fiji",
    "Pháp",
    "Gabon",
    "Anh",
    "Greneda",
    "Gruzia",
    "Guiana thuộc Pháp",
    "Ghana",
    "Gibraltar",
    "Gambia",
    "Guinea",
    "Hy Lạp",
    "Guatemala",
    "Guam",
    "Guyana",
    "Honduras",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Người israel",
    "Ấn Độ",
    "Iraq",
    "Iran",
    "Nước Iceland",
    "Nước Ý",
    "Côte d'Ivoire",
    "Jamaica",
    "Jordan",
    "Nhật Bản",
    "Kenya",
    "Kyrgyzstan",
    "Campuchia",
    "Bắc Triều Tiên",
    "Hàn Quốc",
    "Cộng hòa Côte d'Ivoire",
    "Kuwait",
    "Kazakhstan",
    "Nước Lào",
    "Lebanon",
    "thánh lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Litva",
    "Luxembourg",
    "Latvia",
    "Libia",
    "Ma-rốc",
    "Monacô",
    "Moldova",
    "Madagascar",
    "Mali",
    "Myanmar",
    "Mông Cổ",
    "Ma Cao",
    "Montserrat",
    "malta",
    "Quần đảo Mariana",
    "Martinique",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Nicaragua",
    "Nước Hà Lan",
    "Na Uy",
    "Nepal",
    "Antille thuộc Hà Lan",
    "Nauru",
    "New Zealand",
    "Ô-man",
    "Panama",
    "Peru",
    "Polynesia thuộc Pháp",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Ba Lan",
    "Puerto Rico",
    "Bồ Đào Nha",
    "Paraguay",
    "Qatar",
    "Đoàn tụ",
    "Romania",
    "Nga",
    "Ả Rập Saudi",
    "Quần đảo Solomon",
    "Seychelles",
    "Sudan",
    "Thụy Điển",
    "Singapore",
    "Slovenia",
    "Slovakia",
    "Sierra Leone",
    "san marino",
    "Đông Samoa (Hoa Kỳ)",
    "Tây Samoa",
    "Sénégal",
    "somali",
    "Surinam",
    "Sao Tome và Principe",
    "El Salvador",
    "Syria",
    "Swaziland",
    "Chad",
    "Đi",
    "Nước Thái Lan",
    "Tajikistan",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Thổ Nhĩ Kỳ",
    "Trinidad và Tobago",
    "Tanzania",
    "Ukraina",
    "Uganda",
    "HOA KỲ",
    "Uruguay",
    "Uzbekistan",
    "Thánh Vincent",
    "Venezuela",
    "Việt Nam",
    "Yêmen",
    "Nam Tư",
    "Nam Phi",
    "Zambia",
    "Zaire",
    "Zimbabwe",
  ];
  static List<String> nameForLanguageHi = const [
    "चीन",
    "ताइवान, चीन",
    "चीन हांगकांग",
    "अंडोरा गणराज्य",
    "संयुक्त अरब अमीरात",
    "अफगानिस्तान",
    "अण्टीगुआ और बारबूडा",
    "एंगुइला",
    "अल्बानिया",
    "आर्मेनिया",
    "आरोहण",
    "अंगोला",
    "अर्जेंटीना",
    "ऑस्ट्रिया",
    "ऑस्ट्रेलिया",
    "अज़रबैजान",
    "बारबाडोस",
    "बांग्लादेश",
    "बेल्जियम",
    "बुर्किना फासो",
    "बुल्गारिया",
    "बहरीन",
    "बुरुंडी",
    "बेनिन",
    "फिलिस्तीन",
    "बरमूडा",
    "ब्रुनेई",
    "बोलीविया",
    "ब्राजील",
    "बहामास",
    "बोत्सवाना",
    "बेलारूस",
    "बेलीज़",
    "कनाडा",
    "केमन द्वीपसमूह",
    "केन्द्रीय अफ़्रीकी गणराज्य",
    "कांगो",
    "स्विट्ज़रलैंड",
    "द्वीप",
    "चिली",
    "कैमरून",
    "कोलंबिया",
    "कोस्टा रिका",
    "चेक",
    "क्यूबा",
    "साइप्रस",
    "चेक",
    "जर्मनी",
    "जिबूती",
    "डेनमार्क",
    "डोमिनिकन गणराज्य",
    "अल्जीरिया",
    "इक्वाडोर",
    "एस्टोनिया",
    "मिस्र",
    "स्पेन",
    "इथियोपिया",
    "फ़िनलैंड",
    "फ़िजी",
    "फ्रांस",
    "गैबॉन",
    "यू.के",
    "ग्रेनेडा",
    "जॉर्जिया",
    "फ्रेंच गयाना",
    "घाना",
    "जिब्राल्टर",
    "गाम्बिया",
    "गिनी",
    "यूनान",
    "ग्वाटेमाला",
    "गुआम",
    "गुयाना",
    "होंडुरास",
    "हैती",
    "हंगरी",
    "इंडोनेशिया",
    "आयरलैंड",
    "इजराइल",
    "भारत",
    "इराक",
    "ईरान",
    "आइसलैंड",
    "इटली",
    "कोटे डी आइवर",
    "जमैका",
    "जॉर्डन",
    "जापान",
    "केन्या",
    "किर्गिस्तान",
    "कंबोडिया",
    "उत्तर कोरिया",
    "दक्षिण कोरिया",
    "कोटे डी आइवर गणराज्य",
    "कुवैत",
    "कजाकिस्तान",
    "लाओस",
    "लेबनान",
    "सेंट लूसिया",
    "लिकटेंस्टीन",
    "श्रीलंका",
    "लाइबेरिया",
    "लेसोथो",
    "लिथुआनिया",
    "लक्ज़मबर्ग",
    "लातविया",
    "लीबिया",
    "मोरक्को",
    "मोनाको",
    "मोल्दोवा",
    "मेडागास्कर",
    "माली",
    "म्यांमार",
    "मंगोलिया",
    "मकाओ",
    "मोंटसेराट",
    "माल्टा",
    "मारियाना द्वीप समूह",
    "मार्टीनिक",
    "मॉरीशस",
    "मालदीव",
    "मलावी",
    "मेक्सिको",
    "मलेशिया",
    "मोज़ाम्बिक",
    "नामीबिया",
    "नाइजर",
    "नाइजीरिया",
    "निकारागुआ",
    "नीदरलैंड",
    "नॉर्वे",
    "नेपाल",
    "नीदरलैंड्स एंटाइल्स",
    "नाउरू",
    "न्यूज़ीलैंड",
    "ओमान",
    "पनामा",
    "पेरू",
    "फ़्रेंच पोलिनेशिया",
    "पापुआ न्यू गिनी",
    "फिलीपींस",
    "पाकिस्तान",
    "पोलैंड",
    "प्यूर्टो रिको",
    "पुर्तगाल",
    "पराग्वे",
    "कतर",
    "पुनर्मिलन",
    "रोमानिया",
    "रूस",
    "सऊदी अरब",
    "सोलोमन इस्लैंडस",
    "सेशेल्स",
    "सूडान",
    "स्वीडन",
    "सिंगापुर",
    "स्लोवेनिया",
    "स्लोवाकिया",
    "सेरा लिओन",
    "सैन मारिनो",
    "पूर्वी समोआ (यूएसए)",
    "पश्चिमी समोआ",
    "सेनेगल",
    "सोमालिया",
    "सूरीनाम",
    "साओ टोमे और प्रिंसिपे",
    "अल साल्वाडोर",
    "सीरिया",
    "स्वाज़ीलैंड",
    "चाड",
    "चल देना",
    "थाईलैंड",
    "ताजिकिस्तान",
    "तुर्कमेनिस्तान",
    "ट्यूनीशिया",
    "टोंगा",
    "तुर्किये",
    "त्रिनिदाद और टोबैगो",
    "तंजानिया",
    "यूक्रेन",
    "युगांडा",
    "यूएसए",
    "उरुग्वे",
    "उज़्बेकिस्तान",
    "सेंट विंसेंट",
    "वेनेजुएला",
    "वियतनाम",
    "यमन",
    "यूगोस्लाविया",
    "दक्षिण अफ्रीका",
    "जाम्बिया",
    "ज़ैरे",
    "जिम्बाब्वे",
  ];
  static List<String> nameForLanguageTh = const [
    "จีน",
    "ไต้หวันจีน"
        "จีนฮ่องกง",
    "สาธารณรัฐอันดอร์รา"
        "สหรัฐอาหรับเอมิเรตส์",
    "อัฟกานิสถาน",
    "แอนติกาและบาร์บูดา"
        "แองกวิลลา",
    "แอลเบเนีย",
    "อาร์เมเนีย",
    "เสด็จขึ้นสู่สวรรค์",
    "แองโกลา",
    "อาร์เจนตินา",
    "ออสเตรีย",
    "ออสเตรเลีย",
    "อาเซอร์ไบจาน"
        "บาร์เบโดส",
    "บังคลาเทศ",
    "เบลเยียม",
    "บูร์กินาฟาโซ"
        "บัลแกเรีย"
        "บาห์เรน",
    "บุรุนดี",
    "เบนิน"
        "ปาเลสไตน์",
    "เบอร์มิวดา",
    "บรูไน"
        "โบลิเวีย",
    "บราซิล",
    "บาฮามาส",
    "บอตสวานา",
    "เบลารุส"
        "เบลีซ",
    "แคนาดา",
    "หมู่เกาะเคย์เเมน",
    "สาธารณรัฐอัฟริกากลาง"
        "คองโก",
    "สวิตเซอร์แลนด์",
    "เกาะ",
    "ชิลี",
    "แคเมอรูน",
    "โคลัมเบีย",
    "คอสตาริกา",
    "เช็ก",
    "คิวบา",
    "ไซปรัส",
    "เช็ก",
    "เยอรมนี",
    "จิบูตี",
    "เดนมาร์ก",
    "สาธารณรัฐโดมินิกัน",
    "แอลจีเรีย",
    "เอกวาดอร์",
    "เอสโตเนีย",
    "อียิปต์",
    "สเปน",
    "เอธิโอเปีย"
        "ฟินแลนด์",
    "ฟิจิ",
    "ฝรั่งเศส",
    "กาบอง",
    "สหราชอาณาจักร"
        "เกรเนดา",
    "จอร์เจีย"
        "เฟรนช์เกีย",
    "กานา"
        "ยิบรอลตาร์",
    "แกมเบีย",
    "กินี",
    "กรีซ",
    "กัวเตมาลา",
    "กวม",
    "กายอานา",
    "ฮอนดูรัส",
    "เฮติ",
    "ฮังการี",
    "อินโดนีเซีย",
    "ไอร์แลนด์",
    "อิสราเอล",
    "อินเดีย",
    "อิรัก",
    "อิหร่าน",
    "ไอซ์แลนด์",
    "อิตาลี",
    "โกตดิวัวร์",
    "จาเมกา",
    "จอร์แดน",
    "ญี่ปุ่น",
    "เคนยา",
    "คีร์กีซสถาน",
    "กัมพูชา",
    "เกาหลีเหนือ",
    "เกาหลีใต้",
    "สาธารณรัฐโกตดิวัวร์"
        "คูเวต",
    "คาซัคสถาน",
    "ลาว",
    "เลบานอน",
    "เซนต์ลูเซีย",
    "ลิกเตนสไตน์",
    "ศรีลังกา",
    "ไลบีเรีย",
    "เลโซโท",
    "ลิทัวเนีย",
    "ลักเซมเบิร์ก",
    "ลัตเวีย",
    "ลิเบีย",
    "โมร็อกโก"
        "โมนาโก",
    "มอลโดวา"
        "มาดากัสการ์",
    "มาลี"
        "พม่า",
    "มองโกเลีย"
        "มาเก๊า",
    "มอนต์เซอร์รัต",
    "มอลตา",
    "หมู่เกาะมาเรียนา"
        "มาร์ตินีก",
    "มอริเชียส",
    "มัลดีฟส์",
    "มาลาวี",
    "เม็กซิโก",
    "มาเลเซีย",
    "โมซัมบิก",
    "นามิเบีย",
    "ไนเจอร์",
    "ไนจีเรีย",
    "นิการากัว",
    "เนเธอร์แลนด์",
    "นอร์เวย์",
    "เนปาล",
    "เนเธอร์แลนด์",
    "นาอูรู",
    "นิวซีแลนด์",
    "โอมาน",
    "ปานามา",
    "เปรู",
    "เฟรนช์โปลินีเซีย",
    "ปาปัวนิวกินี",
    "ฟิลิปปินส์",
    "ปากีสถาน",
    "โปแลนด์",
    "เปอร์โตริโก้",
    "โปรตุเกส",
    "ประเทศปารากวัย",
    "กาตาร์",
    "เรอูนียง",
    "โรมาเนีย"
        "รัสเซีย",
    "ซาอุดิอาราเบีย",
    "หมู่เกาะโซโลมอน",
    "เซเชลส์",
    "ซูดาน",
    "สวีเดน",
    "สิงคโปร์",
    "สโลวีเนีย",
    "สโลวาเกีย",
    "เซียร์ราลีโอน"
        "ซานมารีโน",
    "ซามัวตะวันออก (สหรัฐอเมริกา)"
        "ซามัวตะวันตก"
        "เซเนกัล",
    "โซมาเลีย",
    "สุรินทร์"
        "เซาตูเมและปรินซิปี"
        "เอลซัลวาดอร์",
    "ซีเรีย",
    "สวาซิแลนด์",
    "ชาด"
        "ไป",
    "ประเทศไทย",
    "ทาจิกิสถาน"
        "เติร์กเมนิสถาน",
    "ตูนิเซีย"
        "ตองกา",
    "ตุรกี"
        "ตรินิแดดและโตเบโก",
    "แทนซาเนีย",
    "ยูเครน",
    "ยูกันดา",
    "สหรัฐอเมริกา",
    "อุรุกวัย",
    "อุซเบกิสถาน",
    "เซนต์วินเซนต์",
    "เวเนซุเอลา",
    "เวียดนาม",
    "เยเมน",
    "ยูโกสลาเวีย",
    "แอฟริกาใต้",
    "แซมเบีย",
    "ซาอีร์",
    "ซิมบับเว",
  ];

  static List<String> nameForLanguageFil = const [
    "China",
    "Taiwan, China",
    "China Hong Kong",
    "Republika ng Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua at Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Pag-akyat",
    "Angola",
    "Argentina",
    "Austria",
    "Australia",
    "Azerbaijan",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Palestine",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Brazil",
    "Bahamas",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Mga Isla ng Cayman",
    "Central African Republic",
    "Congo",
    "Switzerland",
    "Isla",
    "Chile",
    "Cameroon",
    "Colombia",
    "costa rica",
    "Czech",
    "Cuba",
    "Cyprus",
    "Czech",
    "Alemanya",
    "Djibouti",
    "Denmark",
    "Republikang Dominikano",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Ehipto",
    "Espanya",
    "Ethiopia",
    "Finland",
    "Fiji",
    "France",
    "Gabon",
    "U.K",
    "Greneda",
    "Georgia",
    "French Guiana",
    "Ghana",
    "Gibraltar",
    "Gambia",
    "Guinea",
    "Gresya",
    "Guatemala",
    "Guam",
    "Guyana",
    "Honduras",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "India",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Côte d'Ivoire",
    "Jamaica",
    "Jordan",
    "Hapon",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Hilagang Korea",
    "South Korea",
    "Republika ng Côte d'Ivoire",
    "Kuwait",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "santo lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Madagascar",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Montserrat",
    "malta",
    "Mga Isla ng Mariana",
    "Martinique",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Netherlands Antilles",
    "Nauru",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "Pranses na Polynesia",
    "Papua New Guinea",
    "ang Pilipinas",
    "Pakistan",
    "Poland",
    "Puerto Rico",
    "Portugal",
    "Paraguay",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "slovenia",
    "Slovakia",
    "Sierra Leone",
    "san marino",
    "Eastern Samoa (USA)",
    "Western Samoa",
    "Senegal",
    "somalia",
    "Surinam",
    "Sao Tome at Principe",
    "El Salvador",
    "Syria",
    "Swaziland",
    "Chad",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Türkiye",
    "Trinidad at Tobago",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "USA",
    "Uruguay",
    "Uzbekistan",
    "Saint Vincent",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Yugoslavia",
    "Timog Africa",
    "Zambia",
    "Zaire",
    "Zimbabwe",
  ];
}

extension Extension on Country {
  String nameForLanguage() {
    if (Tools.getCurLanguage() == LanguageType.zh) {
      return Country.nameForLanguageZh[index];
    } else if (Tools.getCurLanguage() == LanguageType.pt) {
      return Country.nameForLanguagePt[index];
    } else if (Tools.getCurLanguage() == LanguageType.es) {
      return Country.nameForLanguageEs[index];
    } else if (Tools.getCurLanguage() == LanguageType.en) {
      return Country.nameForLanguageEn[index];
    } else if (Tools.getCurLanguage() == LanguageType.vn) {
      return Country.nameForLanguageVn[index];
    } else if (Tools.getCurLanguage() == LanguageType.hi) {
      return Country.nameForLanguageHi[index];
    } else if (Tools.getCurLanguage() == LanguageType.th) {
      return Country.nameForLanguageTh[index];
    } else if (Tools.getCurLanguage() == LanguageType.fil) {
      return Country.nameForLanguageFil[index];
    }
    return "";
  }
}
